USE QUANLIQUYTUTHIEN
GO
--TRIGGER
create TRIGGER TG_NGAYNHANCHUC ON NHANVIEN FOR INSERT
AS 
BEGIN
	DECLARE @MANV CHAR(10), @NGAYNHAMCHUC DATE
	IF((SELECT NHANVIEN.NGAYNHAMCHUC 
	FROM NHANVIEN INNER JOIN INSERTED 
	ON NHANVIEN.NGAYNHAMCHUC = INSERTED.NGAYNHAMCHUC) > GETDATE())
		BEGIN
			PRINT N'NGÀY NHẬN CHỨC KHÔNG ĐƯỢC LỚN HƠN NGÀY HIỆN TẠI'
			ROLLBACK TRAN
		END
END

GO
create TRIGGER TG_VATTAITRO ON THONGTINTAITRO FOR UPDATE
AS
BEGIN
	IF((SELECT THONGTINTAITRO.VATTAITRO 
	FROM THONGTINTAITRO INNER JOIN INSERTED 
	ON THONGTINTAITRO.VATTAITRO = INSERTED.VATTAITRO) = '0')
		BEGIN
			PRINT N'SỐ LƯỢNG VẬT TÀI TRỢ KHÔNG ĐƯỢC 0 HOẶC NULL'
			ROLLBACK TRAN
		END
END
 GO
alter TRIGGER tg_HOANCANH on DOITUONGTHUHUONG
FOR DELETE
AS
BEGIN
	RAISERROR (N'Dữ liệu không được xoá',16,1)
	ROLLBACK TRAN
END
GO
--Stored Procedure CÓ tham số
alter PROC sp_THEMDOITUONG(@madt char(10),
                            @tenndt nvarchar(100),
							@nghenghiep nvarchar(100),
							@hoancanh nvarchar(200))
AS
INSERT INTO DOITUONGTHUHUONG
VALUES(@madt,@tenndt,@nghenghiep,@hoancanh)
exec sp_THEMDOITUONG'DT006', N'HỒ NGUYỄN DUY TRÍ',N'bán kẹo kéo',N'còn thiếu nợ'
GO
CREATE PROC SP_INSERT_NHANVIEN
	@MANHANVIEN			CHAR(10),
	@TENNHANVIEN		NVARCHAR(100),
	@DCNHANVIEN         NVARCHAR(100),
	@SDTNHANVIEN        CHAR(10),
	@NGAYNHAMCHUC       DATE,
	@MACHUCVU           CHAR(10)
AS
	IF(NOT EXISTS(SELECT MANV FROM NHANVIEN WHERE MANV=@MANHANVIEN))
		INSERT	INTO	NHANVIEN	VALUES	
		(@MANHANVIEN, @TENNHANVIEN, @DCNHANVIEN , @SDTNHANVIEN, @NGAYNHAMCHUC, @MACHUCVU)
	ELSE
		RAISERROR(N'ĐÃ CÓ NHÂN VIÊN NÀY RỒI', 16, 1)
go
ALTER PROC timmanv 
@manvout char(10) out
AS 
BEGIN
	DECLARE @manv char(10)
	SET @manv= 'NV001'
	DECLARE @i int 
	SET @i=1
	WHILE exists (SELECT MANV FROM NHANVIEN WHERE MANV=@manv)
	begin
		set @i=@i+1;
		set @manv='NV'+REPLICATE('0',3- LEN(cast (@i as nvarchar)))+cast (@i as nvarchar)
	end
	set @manvout=@manv
end 
EXEC timmanv @manvout out 
SELECT @manvout

GO
--FUNCTION
alter FUNCTION fn_DemSoNhanVien(@machucvu char(10)) 
RETURNS int AS 
BEGIN 
 DECLARE @ret int; 
 SELECT @ret = count(*) FROM NHANVIEN WHERE MACHUCVU = @machucvu; 
 IF (@ret IS NULL) 
   SET @ret = 0; 
 RETURN @ret; 
END
select dbo.fn_DemSoNhanVien ('002')
go
alter FUNCTION fn_DanhSachNhanVien (@machucvu char(10)) 
RETURNS TABLE AS RETURN 
( 
 SELECT * 
 FROM NHANVIEN 
 WHERE MACHUCVU = @machucvu 
)
go
select * from fn_DanhSachNhanVien ('002')
CREATE FUNCTION fn_HoTro (@vathotro nvarchar(100))
RETURNS TABLE RETURN
        SELECT NHT.MANHT,NHT.TENNHT,NHT.ĐCNHT,NHT.SĐTNHT,HT.VATHOTRO,HT.NGAYHOTRO,DT.MAĐT,DT.TENĐT
		FROM NHAHAOTAM NHT INNER JOIN HOTRO HT
		   ON HT.MANHT=NHT.MANHT INNER JOIN DOITUONGTHUHUONG DT
		   ON DT.MAĐT=HT.MAĐT
		WHERE HT.VATHOTRO=@vathotro
go
select *from fn_HoTro (N'Gạo')
